//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNC_Pathfinder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("880000")]
        public int CNC_Axes_Step_Dim_X {
            get {
                return ((int)(this["CNC_Axes_Step_Dim_X"]));
            }
            set {
                this["CNC_Axes_Step_Dim_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("660000")]
        public int CNC_Axes_Step_Dim_Y {
            get {
                return ((int)(this["CNC_Axes_Step_Dim_Y"]));
            }
            set {
                this["CNC_Axes_Step_Dim_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220000")]
        public int CNC_Axes_Step_Dim_Z {
            get {
                return ((int)(this["CNC_Axes_Step_Dim_Z"]));
            }
            set {
                this["CNC_Axes_Step_Dim_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double CNC_Axes_Units_Dim_X {
            get {
                return ((double)(this["CNC_Axes_Units_Dim_X"]));
            }
            set {
                this["CNC_Axes_Units_Dim_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double CNC_Axes_Units_Dim_Y {
            get {
                return ((double)(this["CNC_Axes_Units_Dim_Y"]));
            }
            set {
                this["CNC_Axes_Units_Dim_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double CNC_Axes_Units_Dim_Z {
            get {
                return ((double)(this["CNC_Axes_Units_Dim_Z"]));
            }
            set {
                this["CNC_Axes_Units_Dim_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2200")]
        public double CNC_Step_Resolution_X {
            get {
                return ((double)(this["CNC_Step_Resolution_X"]));
            }
            set {
                this["CNC_Step_Resolution_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2200")]
        public double CNC_Step_Resolution_Y {
            get {
                return ((double)(this["CNC_Step_Resolution_Y"]));
            }
            set {
                this["CNC_Step_Resolution_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2200")]
        public double CNC_Step_Resolution_Z {
            get {
                return ((double)(this["CNC_Step_Resolution_Z"]));
            }
            set {
                this["CNC_Step_Resolution_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double CNC_Feedrate_Min {
            get {
                return ((double)(this["CNC_Feedrate_Min"]));
            }
            set {
                this["CNC_Feedrate_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1300")]
        public double CNC_Feedrate_Max {
            get {
                return ((double)(this["CNC_Feedrate_Max"]));
            }
            set {
                this["CNC_Feedrate_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public int CNC_Laser_MaxPower {
            get {
                return ((int)(this["CNC_Laser_MaxPower"]));
            }
            set {
                this["CNC_Laser_MaxPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CNC_Units {
            get {
                return ((int)(this["CNC_Units"]));
            }
            set {
                this["CNC_Units"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CNC_InitialHomePosition {
            get {
                return ((int)(this["CNC_InitialHomePosition"]));
            }
            set {
                this["CNC_InitialHomePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CNC_FeedrateMode {
            get {
                return ((int)(this["CNC_FeedrateMode"]));
            }
            set {
                this["CNC_FeedrateMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int CNC_Multiblocks_Size {
            get {
                return ((int)(this["CNC_Multiblocks_Size"]));
            }
            set {
                this["CNC_Multiblocks_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int COM_Baudrate {
            get {
                return ((int)(this["COM_Baudrate"]));
            }
            set {
                this["COM_Baudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int COM_Lineterminator {
            get {
                return ((int)(this["COM_Lineterminator"]));
            }
            set {
                this["COM_Lineterminator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COM_WaitForOK {
            get {
                return ((bool)(this["COM_WaitForOK"]));
            }
            set {
                this["COM_WaitForOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TP_ToolType {
            get {
                return ((int)(this["TP_ToolType"]));
            }
            set {
                this["TP_ToolType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TP_Laser_Power_Cut {
            get {
                return ((int)(this["TP_Laser_Power_Cut"]));
            }
            set {
                this["TP_Laser_Power_Cut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TP_Laser_Power_Idle {
            get {
                return ((int)(this["TP_Laser_Power_Idle"]));
            }
            set {
                this["TP_Laser_Power_Idle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TP_Drill_Speed {
            get {
                return ((int)(this["TP_Drill_Speed"]));
            }
            set {
                this["TP_Drill_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public double TP_Drill_Down_UnitsHeight_Z {
            get {
                return ((double)(this["TP_Drill_Down_UnitsHeight_Z"]));
            }
            set {
                this["TP_Drill_Down_UnitsHeight_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TP_Drill_Up_UnitsHeight_Z {
            get {
                return ((double)(this["TP_Drill_Up_UnitsHeight_Z"]));
            }
            set {
                this["TP_Drill_Up_UnitsHeight_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1300")]
        public double TP_RapidFeedrate {
            get {
                return ((double)(this["TP_RapidFeedrate"]));
            }
            set {
                this["TP_RapidFeedrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double TP_LinearFeedrate {
            get {
                return ((double)(this["TP_LinearFeedrate"]));
            }
            set {
                this["TP_LinearFeedrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double TP_ToolDiameter_Precision {
            get {
                return ((double)(this["TP_ToolDiameter_Precision"]));
            }
            set {
                this["TP_ToolDiameter_Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double TP_ToolDiameter_Roughing {
            get {
                return ((double)(this["TP_ToolDiameter_Roughing"]));
            }
            set {
                this["TP_ToolDiameter_Roughing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TP_Laser_Height_Precision {
            get {
                return ((double)(this["TP_Laser_Height_Precision"]));
            }
            set {
                this["TP_Laser_Height_Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double TP_Laser_Height_Roughing {
            get {
                return ((double)(this["TP_Laser_Height_Roughing"]));
            }
            set {
                this["TP_Laser_Height_Roughing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1400")]
        public int TP_Laser_Power_Contour {
            get {
                return ((int)(this["TP_Laser_Power_Contour"]));
            }
            set {
                this["TP_Laser_Power_Contour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double TP_Contour_Feedrate {
            get {
                return ((double)(this["TP_Contour_Feedrate"]));
            }
            set {
                this["TP_Contour_Feedrate"] = value;
            }
        }
    }
}
